# Generated by Django 3.0.7 on 2020-10-25 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeveType', models.BooleanField(default=True)),
                ('pantsType', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('clothImage', models.ImageField(blank=True, null=True, upload_to='cloth/')),
                ('price', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClothType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ViewOfUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look', models.IntegerField(default=0)),
                ('resently', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.Cloth')),
            ],
        ),
        migrations.CreateModel(
            name='StandardFit_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('chest', models.IntegerField()),
                ('shoulder', models.IntegerField()),
                ('sleeve', models.IntegerField(blank=True, null=True)),
                ('clothGeneral', models.IntegerField()),
                ('clothType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloth.ClothType')),
            ],
        ),
        migrations.CreateModel(
            name='StandardFit_down',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('waistWidth', models.IntegerField()),
                ('totalHeight', models.IntegerField()),
                ('clothType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloth.ClothType')),
            ],
        ),
        migrations.AddField(
            model_name='cloth',
            name='multyFitTypePants',
            field=models.ManyToManyField(blank=True, null=True, to='cloth.StandardFit_down'),
        ),
        migrations.AddField(
            model_name='cloth',
            name='multyFitTypeSleeve',
            field=models.ManyToManyField(blank=True, null=True, to='cloth.StandardFit_up'),
        ),
    ]
