# Generated by Django 3.1.2 on 2020-10-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingBasket',
        ),
    ]
